# Generated by Django 2.1.1 on 2018-12-04 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APCT', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Aisle',
        ),
        migrations.DeleteModel(
            name='Camera',
        ),
        migrations.DeleteModel(
            name='Product',
        ),
        migrations.RemoveField(
            model_name='store',
            name='address',
        ),
        migrations.RemoveField(
            model_name='store',
            name='name',
        ),
        migrations.AddField(
            model_name='store',
            name='number',
            field=models.CharField(default=2, max_length=20),
            preserve_default=False,
        ),
    ]
