# Generated by Django 2.1.1 on 2018-12-04 02:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('APCT', '0002_auto_20181203_2133'),
    ]

    operations = [
        migrations.CreateModel(
            name='Aisle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aisle_number', models.IntegerField()),
                ('aisle_name', models.CharField(max_length=200)),
                ('aisle_description', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Camera',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('camera_view', models.CharField(help_text='Aerial, overhead..', max_length=200)),
                ('camera_location', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(help_text='Product name', max_length=200)),
            ],
        ),
        migrations.RemoveField(
            model_name='store',
            name='number',
        ),
        migrations.AddField(
            model_name='store',
            name='location',
            field=models.CharField(default=23, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='store',
            name='store_name',
            field=models.CharField(default=23, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='aisle',
            name='camera',
            field=models.ManyToManyField(help_text='cameras this aisle has', to='APCT.Camera'),
        ),
        migrations.AddField(
            model_name='aisle',
            name='product',
            field=models.ManyToManyField(help_text='Select products in this aisle', to='APCT.Product'),
        ),
        migrations.AddField(
            model_name='aisle',
            name='store',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='APCT.Store'),
        ),
    ]
